jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port:
   servlet:
      context-path: /PaquetesTuristicos
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://adn-ceiba-db.mysql.database.azure.com:3306/reservasejecafetero?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      username: ceiba@adn-ceiba-db
      password: vzeN_.nn]P9[k]DaMF:$
      hikari:
         poolName: pool
